### ISSUE TITLE
Why does OCamlRef::to_ocaml take &mut OCamlRuntime?

### ISSUE THREAD

**Issue by tiny-book2** [simplestaking/ocaml-interop#56]
I assume there's a good reason for [`OCamlRef::to_ocaml`](https://docs.rs/ocaml-interop/latest/ocaml_interop/type.OCamlRef.html#method.to_ocaml) to take in a `&mut` reference to the runtime, instead of just `&`:

```
fn to_ocaml<'a>(&self, cr: &'a mut OCamlRuntime) -> OCaml<'a, T>
```

but I was just curious why this actually is? My very rudimentary understanding of how this works is that it's perfectly reasonable to keep multiple `OCaml<T>` values around, so long as you throw them away before you allocate. I would have guessed a `&` reference would be sufficient to guarantee this so long as any function that allocates still takes a `&mut` runtime?

**Comment by tizoc** [comment]
Hi @tiny-book2. The `to_ocaml` implementation for `OCamlRef` doesn't need exclusive access to the OCaml runtime because it will not allocate anything (same as for int conversion). But the signature defined by the trait does, because most conversion will need to perform allocations in the OCaml heap, and if that happens, all un-rooted references will be invalidated. Requiring an exclusive reference to the OCaml runtime handle enforces that invalidation through the typechecker.
